Feat: change example with ECL template
aeecleclair/ldap-overleaf-sl pull request #4
Opened 2024-09-29 22:59 UTC by Rotheem

2024-10-03 12:27 UTC, Daihecyy approved these changes
Realy good PR

2024-11-12 19:35 UTC, armanddidierjean requested changes

2024-11-12 19:35 UTC, armanddidierjean commented on ldap-overleaf-sl/Dockerfile
> -    ## comment out this line to prevent sed accidently remove the brackets of the email(username) field
Please don't change the formatting of the file. It makes rebases on upstream more complex.

2024-11-12 19:35 UTC, armanddidierjean commented on ldap-overleaf-sl/template_ecl.zip
I think you can delete this file

2024-11-12 23:21 UTC, merged